### PR TITLE
add support-notification test script

### PR DESCRIPTION
**Pull request by weichou1229**
Signed-off-by: Bruce <weichou1229@gmail.com>

### CODE REVIEW

**Comment by weichou1229** [comment]
@tsconn23 help review test script for support-notification

**Comment by tsconn23** [comment]
@cloudxxx8 -- I am asking @akramtexas to be responsible for verifying this PR as he has the task for bringing the support-notifications into the main repo on his plate.

**Comment by akramtexas** [comment]
Sure thing @tsconn23  I will be glad to take responsibility for verifying this PR.

**Comment by jpwhitemn** [comment]
recheck

**Comment by andyf1967** [comment]
recheck

**Comment by cloudxxx8** [comment]
test has passed
please help review and merge

**Comment by weichou1229** [comment]
@tsconn23 @JPWKU conflict solved , please help recheck .

**Comment by tsconn23** [comment]
@akramtexas Please confirm that the tests in this PR have been run against the Notitifcations service as integrated with the California branch, and that this PR can be approved/merged.

**Comment by weichou1229** [comment]
@tsconn23 Now support-notifications service are test by java's master branch, and other services also use master branch. 
You can watch this comment for why use master branch on backbox-testing : 
https://github.com/edgexfoundry/blackbox-testing/pull/38#issuecomment-407087647

And I think we can create another PR for California release after these three PRs merged: https://github.com/edgexfoundry/blackbox-testing/pull/31, https://github.com/edgexfoundry/blackbox-testing/pull/39, https://github.com/edgexfoundry/blackbox-testing/pull/53

@akramtexas Is California release use docker-support-notifications-go:0.6.1 ?

**Comment by akramtexas** [comment]
@tsconn23 This is to confirm that the tests in this PR have been run against the notifications service as integrated with the California branch. All tests pass with the exception of the two for which the plan is for the test team to open another PR. Those two tests are related to the update each (one each for both "/transmission" and for "/notification") in the RAML in the edgex-go codebase as noted in the comment I had added to [Issue #21](https://github.com/edgexfoundry/support-notifications/issues/21).

**Comment by akramtexas** [comment]
@weichou1229 Yes, that is correct: California release is indeed [using version 0.6.1](https://github.com/akramtexas/edgex-go/blob/1b0fadb24586eb71a2251588c0aa9507a0c0f0ec/version.go).

**Comment by akramtexas** [comment]
- @tsconn23 and @weichou1229 Please note, for fuller context: At this time the tests on the master branch for notifications are being run against the Java version (And those pass 100%), since the Golang version isn't on the master branch yet. **As such, this PR can be approved/merged**.
- Basically, what will need to happen to that end, _separately_, beyond this PR, is that we'll need to coordinate the PRs on the master branch, which means:
1. move notifications over to master branch, and
2. update notifications tests to include the changes to  address Golang changes to those 2 APIs (one each for both "/transmission" and for "/notification").

**Review by akramtexas — APPROVED** [review]

**Pull request merged**
