### PR TITLE
fix assertion's responseTime inconsistent

### PR DESCRIPTION
**Pull request by weichou1229**
change
`tests[\"Response time is less than \"+data.responseTime] = responseTime < 200`
to
`tests[\"Response time is less than \"+data.responseTime] = responseTime < data.responseTime`

Signed-off-by: Bruce <weichou1229@gmail.com>

### CODE REVIEW

**Comment by weichou1229** [comment]
@JPWKU Could you review this PR ?
This is fix for https://github.com/edgexfoundry/edgex-go/issues/481

**Comment by tsconn23** [comment]
@weichou1229 I notice this fix is made against the master branch. The edgex-go issue 481 is for blackbox tests run against the California branch. The fix may still be applicable to master, but we need it in California first to get all the tests in that branch passing.

**Comment by weichou1229** [comment]
@tsconn23 
You mean 
1. I need create branch from California branch and make same script change.
2. Close this PR.

Right?

**Comment by cloudxxx8** [comment]
@weichou1229 yes, Bruce, please create another branch based on California branch, fix the issue, and open a new PR to make the fix into California branch.  Thanks

**Comment by weichou1229** [comment]
close this PR and create new PR based on California branch

**Comment by cloudxxx8** [comment]
@weichou1229 , please re-open this PR, because we still need the fix in master

**Pull request closed without merging**
