### PR TITLE
update docker compose file to v3

### PR DESCRIPTION
**Pull request by weichou1229**
https://github.com/edgexfoundry/blackbox-testing/issues/76

### CODE REVIEW

**Comment by weichou1229** [comment]
@JPWKU 
please help check, it seems docker-compose not support v3 file in arm64
```
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```
https://jenkins.edgexfoundry.org/job/blackbox-verify-cavium-arm64-master/139/console

**Comment by JPWKU** [comment]
I am looking into this, I have a new arm64 image to test out soon.  I'll ping here when I have a job created in the jenkins sandbox.

**Comment by JPWKU** [comment]
@weichou1229 Can you get in touch with the folks at Cavium and find out which docker-compose and docker  versions are running?

**Comment by weichou1229** [comment]
I found a file which you add on ci-management.
https://github.com/edgexfoundry/ci-management/blob/master/jenkins-config/clouds/openstack/Primary/ubuntu18.04-docker-arm64-4c-2g.cfg
I think you can use the latest version. It seems support ubuntu arm64.
Official document:
https://docs.docker.com/install/#supported-platforms
https://docs.docker.com/compose/compose-file/

**Comment by feclare** [comment]
The versions of docker and docker compose:
```
docker-compose --version
docker-compose version 1.8.0, build unknown
```
```
docker version
Client:
Version: 17.03.2-ce
API version: 1.27
Go version: go1.8.3
Git commit: f5ec1e293
Built: Thu Nov 30 14:20:39 2017
OS/Arch: linux/arm64

Server:
Version: dev
API version: 1.36 (minimum version 1.12)
Go version: go1.9.3
```

**Comment by tsconn23** [comment]
recheck

**Review by tsconn23 — APPROVED** [review]
blackbox verify passed on new LF ARM infra. Looks good to me! Good job folks!

**Pull request merged**
