### PR TITLE
Rev'ed notifications to 0.7.0

### PR DESCRIPTION
**Pull request by tsconn23**
#54 

Now that notifications has been merged into the master branch, needed to include it as part of the scripts.

Signed-off-by: Trevor Conn <trevor_conn@dell.com>

### CODE REVIEW

**Review by JPWKU — DISMISSED** [review]
LGTM

**Review by JPWKU — DISMISSED** [review]
LGTM

**Comment by akramtexas** [comment]
👍

**Comment by tsconn23** [comment]
FYI -- This PR won't pass until config-seed-go PR is merged, followed by fix to Notifications that I have to discuss with @akramtexas @xmlviking tomorrow.

**Comment by akramtexas** [comment]
@tsconn23 Sure, let's please discuss the path forward involving (1) config-seed-go PR to be merged, and (2) followed by fix to Notifications.

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Comment by tsconn23** [comment]
recheck

**Review by JPWKU — APPROVED** [review]
LGTM

**Pull request merged**
