### PR TITLE
Remove notification query status=NEW testcase

### LINKED ISSUE #399: Remove the unnecessary notification testcase
The change in [edgexfoundry/edgex-go#2347](https://github.com/edgexfoundry/edgex-go/pull/2347) is a _NORMAL_ notification, as well as a _CRITICAL_ notification, will be processed immediately. Thus, there is no need to test `"Query the unprocessed notifications (status = NEW) with limited returned records"` – the status of the notification will become `PROCESSED` immediately.

### PR DESCRIPTION
**Pull request by jinlinGuan**
fix #399

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
recheck

**Comment by cloudxxx8** [comment]
@jinlinGuan I saw the jjb was changed when you created this PR.
https://github.com/edgexfoundry/ci-management/commit/514586742eea3f56109f80b22d750e9b81641abd
Could you please try to re-open this PR and see the invalid checker is still there?
Thanks

**Comment by jinlinGuan** [comment]
Close this PR and open a new one.

**Pull request closed without merging**
