### PR TITLE
Add "echo" in shell script to avoid newman error

### LINKED ISSUE #355: Add "echo" line in shell script to avoid newman error
Same as #334, but also need to fix on Master branch.

### PR DESCRIPTION
**Pull request by jinlinGuan**
Fix https://github.com/edgexfoundry/blackbox-testing/issues/355

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

### CODE REVIEW

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
recheck

**Comment by bnevis-i** [comment]
@cloudxxx8 Jenkins is having serious issues at the moment.  How is blackbox testing doing locally with the patched docker-compose and start-edgex.sh on master?

**Comment by cloudxxx8** [comment]
@bnevis-i We verified core-data on this branch locally without security setting, but hasn't run with the patched docker-compose.

**Comment by cloudxxx8** [comment]
oh, since #349 has been merged, we were running against the patched docker-compose file well locally

**Comment by cloudxxx8** [comment]
recheck

**Comment by lranjbar** [comment]
recheck

**Comment by eb-oss** [comment]
recheck

**Comment by eb-oss** [comment]
recheck

**Pull request merged**
