### PR TITLE
issue-174 Add OperatingState when posting ProvisionWatcher

### LINKED ISSUE #174: Metadata/ProvisionWatcher Import: OperatingState Is Empty
During the ProvisionWatcher step of metadata-import, OperatingState is not specified and is therefore empty. It should either be `ENABLED` or `DISABLED`. Sample JSON definition from `core-metadata-importer.postman_collection.json`

```
"  \"_class\": \"org.edgexfoundry.domain.meta.ProvisionWatcher\",",
"  \"name\": \"lonmark watcher\",",
"  \"identifiers\": {",
"    \"MAC\": \"00-05-1C-C1-99-99\",",
"    \"HTTP\": \"10.0.0.4\"",
"  },",
"  \"origin\": 1471806386919,",
"  \"profile\": {",
"    \"name\": \"variable speed motor profile\"",
"  },",
"  \"service\": {",
"    \"name\": \"home variable speed motor device service\"",
"  }",
```
As you can see, no `OperatingState` field. Interestingly I found this because an error is correctly thrown when running core-metadata with Redis database. No error is thrown when using Mongo, which means there's a bug somewhere in metadata as well.

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

fix #174

### CODE REVIEW

**Review by weichou1229 — DISMISSED** [review]
LGTM

**Review by tsconn23 — CHANGES_REQUESTED** [review]
@cherrycl Can you please change all instances of `OperatingState` to `operatingState`

**Comment by cherrycl** [comment]
> @cherrycl Can you please change all instances of `OperatingState` to `operatingState`

@tsconn23 Done for changing `OperatingState` to `operatingState`.

**Review by tsconn23 — DISMISSED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
