### PR TITLE
Update DeviceProfile collections to use renamed properties  name

### PR DESCRIPTION
**Pull request by difince**
issue: https://github.com/edgexfoundry/blackbox-testing/issues/220
Signed-off-by: difince <dianaa@vmware.com>

### CODE REVIEW

**Review by weichou1229 — COMMENTED** [review]
These device profiles should update properties too.
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/device-sdk_sample_profile.yaml
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/sample_profile.yaml
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/sample_profile_duplicated_command.yaml

**Comment by difince** [comment]
It looks my "global" search, was not that global ... Thank you

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
