### PR TITLE
Fix scripts which cannot detect failed test cases

### LINKED ISSUE #97: Some scripts cannot detect failed test cases
When I done the blackbox-testing for Delhi, I found some script cannot detect failed test cases.
For example,
image
If the result is not 423, it is still passed.  Some errors were passed by this kind of script, so there are some real issues we haven't recorded.

In this test, the following should be indicated as failed but passed
_core-data_
image
_core-metadata_
image
image
_core-command_
image
image

It might be better to review other test scripts one by one.

### PR DESCRIPTION
**Pull request by FelixTing**
Fix #97 
Also update collection format version to 2.1

### CODE REVIEW

**Comment by FelixTing** [comment]
@weichou1229 please help review, thanks

**Comment by FelixTing** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by cloudxxx8** [comment]
please fix this issue on master only

**Pull request closed without merging**
