### PR TITLE
Updated to use new Admin and Operating State APIs

### PR DESCRIPTION
**Pull request by AnthonyMBonafide**
This commit resolves issue #200

Updated the core-command and core-metadata postman collection to align
with changes to the core-command API. See edgexfoundry/edgex-go issue
1244 for context.

Signed-off-by: Anthony M. Bonafide <AnthonyMBonafide@gmail.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
add @cherrycl

**Comment by cherrycl** [comment]
@AnthonyMBonafide I ran the script which you updated. Core-command testcases worked fine, but all change on core-metadata was failed with return code "405 Method Not Allowed". Would you please confirm the issue?

**Comment by AnthonyMBonafide** [comment]
The changes in this PR won't work until [issue 1296](https://github.com/edgexfoundry/edgex-go/issues/1296) in `edgex-go` is resolved.

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by cloudxxx8** [comment]
although https://github.com/edgexfoundry/edgex-go/issues/1296 hasn't been closed, it worked yesterday...
I just noticed the new PR for validation blocked this one

**Pull request merged**
