### PR TITLE
Add tests for GET and DELETE notification by ID

### LINKED ISSUE #229: [Interlock] -- Tests for Delete Notifications By ID
Original Issue https://github.com/edgexfoundry/edgex-go/issues/1328
Pending PR https://github.com/edgexfoundry/edgex-go/pull/1349

Tests for this endpoint will need to be added.

@cloudxxx8 @lindseysimple

### PR DESCRIPTION
**Pull request by weichou1229**
Add successful case and error case for GET and DELETE notification by ID API

Fix #229

### CODE REVIEW

**Comment by weichou1229** [comment]
This PR work with https://github.com/edgexfoundry/edgex-go/pull/1349

**Comment by cloudxxx8** [comment]
@weichou1229 please rebase this PR and add an empty line on the bottom of the file

**Comment by weichou1229** [comment]
> rebase this PR and add an empty line on the bottom of the file

Done

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
