### PR TITLE
Add operatingState and adminState to service object

### LINKED ISSUE #205: Interlock -- Model Validation Requires Request Integrity
Team -- I have a PR outstanding that encapsulates HTTP request validation within the request models found in `go-mod-core-contracts`

https://github.com/edgexfoundry/go-mod-core-contracts/pull/71

This is the result of quite a bit of discussion in the Core Working Group, the point of which was that we identified that in many cases it was possible to submit a request to our REST APIs that was not valid. The following issue is the one that started this effort

https://github.com/edgexfoundry/blackbox-testing/issues/174

The PR for `go-mod-core-contracts` is complete and I am working on a follow up PR to integrate it into `edgex-go`. As part of my due diligence, I want to run the blackbox tests against the upcoming edgex-go PR. However I have found that we have a lot of issues in our blackbox test scripts with request integrity. Fields that are supposed to have a required value are not populated. Here is an example of the errors thrown by core-metadata when running the `core-metadata-importer` collection via Postman.

```
level=ERROR ts=2019-04-24T16:09:59.889698Z app=edgex-core-metadata source=rest_deviceprofile.go:52 msg="Name cannot be blank"
level=ERROR ts=2019-04-24T16:10:00.453664Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.453818Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.45401Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.453853Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454341Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454429Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454562Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454575Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454587Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454688Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454721Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454847Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455018Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455055Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455148Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.45545Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.993425Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.99348Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.993502Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
```

My ask is to please ensure the following
- For any model that has an OperatingState property, that property needs to be populated with a correct value
- For any model that has an AdminState property, that property needs to be populated with a correct value
- For any model corresponding to an EdgeX entity (device, device profile, addressable, etc) on create, it needs to have a name. On update, it needs to have either an ID or a name.

What is your preferred method for addressing this? Would you like to do a pro-active review of the scripts to ensure required properties are populated? Or would you like me to proceed with the above integration and perform fixes based on what tests break? Since the imports don't even run successfully, A LOT of tests will fail -- if not all of them. Please advise ASAP.

### PR DESCRIPTION
**Pull request by cherrycl**
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

fix #205

### CODE REVIEW

**Comment by tsconn23** [comment]
FYI -- During testing of the core-metadata/device tests the following validation error occurred.

Test `PUT 59 http://localhost:48081/api/v1/device`
Request body ```{
  "id":"57f63243e4b060e2e0dd6ed0",
  "name": "livingroomthermostatdevice",
  "description":"Home automation",
  "adminstate":"LOCKED"
}```
Response body `no supporting protocol specified for device`

This indicates the required protocols for the device have not been specified
https://github.com/edgexfoundry/go-mod-core-contracts/blob/f8b9cd6695633badbdfef91e1ad891eac7132b1e/models/device.go#L139

**Comment by tsconn23** [comment]
Also, I'm having an issue with the core-command-importer collection. It's not actually populating anything in the database. When I look at the core service logging with LogLevel=TRACE, all I see is the ping endpoint getting called four times. I have attached an exported result set from Postman that shows this. 

I realize this is different than the issue this PR is targeted at, but it does make the PR hard to approve since the collection doesn't appear to be acting as it's supposed to. Please correct me if I'm misinterpreting these results.

[core-command-importer.postman_test_run.txt](https://github.com/edgexfoundry/blackbox-testing/files/3130530/core-command-importer.postman_test_run.txt)

**Comment by cherrycl** [comment]
@tsconn23 I fixed the device issue. Please help to verify it again.
For the core-command importer, I found you run the file by 48082 port.
Actually, all of requests in core-command importer are core-metadata API, so you have to use 48081 port.

**Review by tsconn23 — DISMISSED** [review]
Please rebase. LGTM.

**Review by tsconn23 — APPROVED** [review]

**Pull request merged**
