### PR TITLE
Blackbox tests failing in Jenkins

### LINKED ISSUE #282: Blackbox tests failing in Jenkins
From @tsconn23:

> Hi all – This is a heads up that I noticed just now that the blackbox tests in Jenkins stopped working on 18-October.
>
>https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-master/
>
>If you look at the Console Output for one of the failed reports, you’ll see errors like the following
>
>08:00:43 → Test whether the virtual device service exists
>08:00:43   GET http://edgex-device-virtual:49990/api/v1/ping [errored]
>08:00:43      connect ECONNREFUSED 172.17.0.6:49990
>08:00:43 → Test whether the Random-Boolean-Device device profile has been added to metadata
>08:00:43   GET http://edgex-core-metadata:48081/api/v1/deviceprofile/name/Random-Boolean-Device [errored]
>08:00:43      getaddrinfo ENOTFOUND edgex-core-metadata edgex-core-metadata:48081
>08:01:05      getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080
>08:01:05 [errored]
> 
>I went through the Jenkins job definition and then through the relevant scripts in the blackbox-testing repo to see if I could find a commit between the 17th and 18th that would be a candidate for causing the failure, but nothing is jumping out at me.
>
>It’s also my understanding that the blackbox tests are using the docker-compose file below and not the one from developer-scripts/releases/nightly-build/compose-files which has seen a lot of modification.
>
>https://github.com/edgexfoundry/blackbox-testing/blob/master/docker-compose.yml

### PR DESCRIPTION
**Pull request by michaelestrin**
Updates docker-compose.yml used for blackbox testing with changes made
in developer-scripts/releases/nightly-build/compose-files/docker-compose-nexus.yml

Fixes: https://github.com/edgexfoundry/blackbox-testing/issues/282

Signed-off-by: Michael W. Estrin <me@michaelestrin.com>

### CODE REVIEW

**Comment by michaelestrin** [comment]
Do not merge.  Both builds go green but tests are not actually being run. 

https://jenkins.edgexfoundry.org/job/blackbox-verify-security-centos7-blackbox-4c-2g-master/158/console

https://jenkins.edgexfoundry.org/job/blackbox-verify-ubuntu18.04-docker-arm64-4c-2g-master/231/console

Currently troubleshooting...

**Comment by michaelestrin** [comment]
> Do not merge. Both builds go green but tests are not actually being run.

After reviewing the Jenkins build configuration, I see that tests are not actually run here.  I believe this PR is ready for review.  

@cloudxxx8 @cherrycl @tsconn23

**Comment by michaelestrin** [comment]
Updated to increment mongo image version from 1.0.0 to 1.1.0 for both env.sh and arm64_env.sh per @tsconn23

**Review by cloudxxx8 — APPROVED** [review]
LGTM, thanks for figuring out the Mongo version issue here

**Pull request merged**
