### PR TITLE
Set container env to correct latest staging images in nexus

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by tsconn23** [comment]
@JPWKU We can probably close this one, right?

**Comment by JPWKU** [comment]
@tsonn23 Yeah, we will be updating them again otherwise.  Thanks.

**Pull request closed without merging**
