### PR TITLE
rewrite 02 ,96 ,35 ,39 api , test configuration.ValidateCheck is false

### PR DESCRIPTION
**Pull request by weichou1229**
#29 test configuration.ValidateCheck is false

Signed-off-by: Bruce <weichou1229@gmail.com>

### CODE REVIEW

**Comment by weichou1229** [comment]
@tsconn23 I had rewrite test name and description , test assertion  . please review ,thx

**Review by tsconn23 — APPROVED** [review]
I pulled this PR into a local branch and rebuilt the collection in Postman. I then ran the tests using the latest California code and they all passed. I'm curious as to why the "hummidity" reading was renamed to "xxx". Why not just correct the misspelling?

**Comment by tsconn23** [comment]
@weichou1229 @cloudxxx8 This is approved. I'll let you guys merge on your own timeline.

**Comment by weichou1229** [comment]
@tsconn23 use "xxx" , is just mean impossible to use the name as value descriptor.

**Pull request merged**
