### PR TITLE
Point blackbox tests at the new core go services

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by jpwhitemn — CHANGES_REQUESTED** [review]
Jeremy - we are missing support-notifications

**Comment by JPWKU** [comment]
@jpwhitemn Ah I have extras in there we don't have yet correct?

**Comment by jpwhitemn** [comment]
@JPWKU If we are just testing go core services, then we should just have core data, metadata and command.  Those are the only ones we have blackbox tests for right now.  If you want to have all the services (existing or potential listed) then you need to add notifications.  Wasn't sure based on what you were listing.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
@jpwhitemn I'm doing stuff locally but I think we should point the blackbox tests at the images in nexus3.edgexfoundr.org staging registry only.  We want to test daily, but we don't push images to dockerhub daily (yet).

**Comment by JPWKU** [comment]
recheck

**Review by jpwhitemn — APPROVED** [review]

**Pull request merged**
