### PR TITLE
Blackbox Testing for App Functions SDK/Configurable

### PR DESCRIPTION
**Pull request by rsdmike**
Signed-off-by: Mike Johanson <michael.johanson@intel.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@FelixTing please help review this PR

**Review by cherrycl — COMMENTED** [review]
Got permission denied error.
bin/run.sh: line 95: bin/appServiceConfigurableTest.sh: Permission denied
Please change the permission of appServiceConfigurableTest.sh to executable.

**Comment by cherrycl** [comment]
If the update consul is a pre-conditional for trigger pipeline testcases, suggest putting the update consul into the Pre-request Script

**Comment by rsdmike** [comment]
@cherrycl I've updated the permissions for the `appServiceConfigurableTest.sh` file using `git update-index --chmod=+x .\bin\appServiceConfigurableTest.sh`. However, I am on windows, so I can't really tell if permissions are correct since everything is executable on Windows.

**Comment by cherrycl** [comment]
@rsdmike The permission issue for the appServiceConfigurableTest.sh is fixed. Thank you.
By the way, do you intend to update the testcases according to the following comment?

> If the update consul is a pre-conditional for trigger pipeline testcases, suggest putting the update consul into the Pre-request Script

**Comment by rsdmike** [comment]
@cherrycl  Great, glad thats fixed. Help me understand what you are referring to in regards to the pre-request script? Do you mean in postman? Consul is seeded when the app service starts taking care of "Seeding" and Consul is updated in between each test to adjust the pipeline, so i'm not sure it would work in the pre-request part.

**Comment by cherrycl** [comment]
@rsdmike Yes, Pre-request script in postman. If you developed tests on postman UI, you can see it like the attached image.
image

The Pre-request script can send update console API, too. If update consul put to a single request in the main test file, that's mean it is one of our main test focus.

**Comment by cloudxxx8** [comment]
@rsdmike since we are not testing Consul, the REST call to Consul should be considered as some set up steps, not test cases

**Comment by rsdmike** [comment]
Ah, I understand now, yes I can make those changes.

**Review by cherrycl — COMMENTED** [review]
@rsdmike I saw the permission on lots of files has changed to 755, like postman files and config files, could you change them back to original permission?

**Comment by cloudxxx8** [comment]
@rsdmike we have new change request.  please see whether you have chance to fix them.  thanks.

**Comment by rsdmike** [comment]
@cloudxxx8  I'll recreate the PR -- that would be easiest.

**Comment by rsdmike** [comment]
recreated as #271

**Pull request closed without merging**
