### PR TITLE
Add tests to go through Kong

### PR DESCRIPTION
**Pull request by FelixTing**
Modify Postman collections/environments and shell scripts so that the APIs can go through Kong when security is enabled

Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Comment by FelixTing** [comment]
The scripts might still need some twist. Will continue the work when [issue#2267](https://github.com/edgexfoundry/edgex-go/issues/2267)  is resolved.

**Comment by cloudxxx8** [comment]
issue#2267 has been resolved

**Comment by FelixTing** [comment]
Has tested on the sandbox. It’s ready for review.
[https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/](https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/)
[https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/](https://jenkins.edgexfoundry.org/sandbox/view/All/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/)

**Review by tingyuz — APPROVED** [review]
LGTM. Checked Jenkins Job and verified all the existing test cases are passed.

**Comment by FelixTing** [comment]
Hi @bnevis-i, may I know what the status of the code review is?

**Comment by bnevis-i** [comment]
@FelixTing you only need one approving review.  TingYu says it passes so that's good enough for me.

**Review by cloudxxx8 — APPROVED** [review]
Approve this PR based on @tingyuz 's review

**Pull request merged**
