### PR TITLE
Remove core-data test #27 issue #187

### PR DESCRIPTION
**Pull request by tsconn23**
#187 

Signed-off-by: Trevor Conn <trevor_conn@dell.com>

### CODE REVIEW

**Comment by tsconn23** [comment]
https://github.com/edgexfoundry/edgex-go/pull/1209 has been merged. This test will now fail until it is removed.

**Review by weichou1229 — COMMENTED** [review]
@tsconn23 https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L1741
This test script is for Error case. It should remove too.

**Comment by tsconn23** [comment]
> https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L1741

Removed

**Review by weichou1229 — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
