### PR TITLE
Pin to vendor consul image and core-config-seed-go

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Review by tsconn23 — DISMISSED** [review]

**Review by tsconn23 — DISMISSED** [review]

**Review by tsconn23 — APPROVED** [review]
Man, I hope this is it

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Pull request merged**
