### PR TITLE
Document display misaligned

### PR DESCRIPTION
**Pull request by VMware-HaoyuLi**
Document display misaligned

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@VMware-HaoyuLi thanks for correcting this mistake.
However, Fuse is the project code long time ago.  Could you please modify the words to "EdgeX Foundry" or "EdgeX"?  Thanks.

**Comment by VMware-HaoyuLi** [comment]
> @VMware-HaoyuLi thanks for correcting this mistake.
> However, Fuse is the project code long time ago. Could you please modify the words to "EdgeX Foundry" or "EdgeX"? Thanks.

OK. Done.

**Review by cloudxxx8 — DISMISSED** [review]
LGTM

**Comment by cloudxxx8** [comment]
@VMware-HaoyuLi thanks, could you please rebase this PR to include the latest changes?

**Comment by VMware-HaoyuLi** [comment]
> @VMware-HaoyuLi thanks, could you please rebase this PR to include the latest changes?

done

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
