### PR TITLE
Remove mongoSeed

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
Currently testing this out locally.  @feclare was under the impression that seed functionality is in the mongo image now.  I am not sure.

**Comment by JPWKU** [comment]
This is not working locally.

**Comment by weichou1229** [comment]
@JPWKU you can see
https://wiki.edgexfoundry.org/display/FA/Get+EdgeX+Foundry+-+Users
Consul is now incorporated in the config-seed container.  It is no longer needed.
so you can remove it too .

also , this is new docker-compose file for run go version service , it's should update , too.
https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-california-0.5.2.yml

**Comment by tsconn23** [comment]
@weichou1229 Hi Bruce, actually we split Consul back out into its own container for the 0.6.0 release. Long story, but it improves the ability to test the config seed locally on a developer's machine using Docker before they check in code.

Also, @jpwhitemn has created a 0.6.0 version of the docker-compose file
https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-california-0.6.0.yml

**Comment by weichou1229** [comment]
@JPWKU please reference my PR https://github.com/edgexfoundry/blackbox-testing/pull/31 ,
I had migrate docker-compose file to 0.6.0 release , you can update these file :
* docker-compose.yml
* deploy-edgeX.sh
* bin/env.sh
* bin/arm64_env.sh  

after update , it can pass the test verify

**Pull request closed without merging**
