### PR TITLE
Update versions to 1.0.0 in environment scripts

### LINKED ISSUE #91: Update versions to 1.0.0 in environment scripts -- master branch
- arm64_env.sh
- env.sh

Images pointed to 0.7.0 need to be pointed to 1.0.0

Also the scheduler image name needs to be corrected:
- arm64_env = docker-support-scheduler-go-arm64
- env = docker-support-scheduler-go

This needs to be done soon as the PR to update edgex-go has been created.

### PR DESCRIPTION
**Pull request by FelixTing**
Fix #91 
Also correct scheduler image name
Signed-off-by: Felix Ting <felix@iotechsys.com>

### CODE REVIEW

**Comment by FelixTing** [comment]
1.0.0 images hasn't been ready

**Comment by FelixTing** [comment]
About support-scheduler
We don't have APIs and test scripts for support-scheduler right now, so we only test Schedule and Schedule Event CRUD from core-metadata

**Comment by weichou1229** [comment]
recheck

**Comment by FelixTing** [comment]
> recheck

rulesengine images(1.0.0) hasn't been ready

**Comment by tsconn23** [comment]
Created this PR for rules-engine 1.0.0 just now
https://github.com/edgexfoundry/support-rulesengine/pull/38

**Comment by cloudxxx8** [comment]
@tsconn23 and @JPWKU ,
I saw the rulesengine PR has been merged for a while, but the 1.0 docker image hasn't been ready.
Could you please help trigger the build? Or instruct us how to trigger it.  Thanks.

**Comment by JPWKU** [comment]
I can trigger the staging image now for rulesengine.

**Comment by JPWKU** [comment]
@cloudxxx8 , I am not able to do this at the moment, but in this sub pom we need
to replace 0.7.0 with 1.0.0
https://github.com/edgexfoundry/support-rulesengine/blob/master/docker-files/pom.xml
Then it will work
Jeremy

**Comment by cloudxxx8** [comment]
@JPWKU 
https://github.com/edgexfoundry/support-rulesengine/pull/39 opened for this
Please help review and merge, thanks

**Comment by cloudxxx8** [comment]
@JPWKU could you please trigger the build again? Thanks

**Comment by FelixTing** [comment]
recheck

**Comment by JPWKU** [comment]
Hi @cloudxxx8, the support-rulesengine 1.0.0 is available now.

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
Apologies @FelixTing I didn't mean to reset your check.

**Comment by FelixTing** [comment]
The arm64 check failed due to build timed out. 
For related messages from Jenkins console, see below...
01:14:33 open /etc/docker/certs.d/nexus3.edgexfoundry.org:10004: permission denied
01:14:40 Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
01:43:25 Build timed out (after 30 minutes). Marking the build as failed.

@JPWKU Could you please help solve this problem? Or instruct me how to fix it. Thank you.

**Comment by JPWKU** [comment]
I can increase the build timeout.  I will try to do this shortly and let
you know when complete.

**Comment by JPWKU** [comment]
Hmm looks like something extra going on as well.  Can you remove all calls
that do a docker login in the test scripts, they should not be needed.

**Comment by FelixTing** [comment]
image
Do you mean this line?
Just gave it a try, the problem is still there, maybe I did it wrong.

**Comment by JPWKU** [comment]
Yes....I opened a PR against master that does that.  The error is still
there.  I will be able to sit down and really troubleshoot in a few hours.

**Comment by JPWKU** [comment]
recheck

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Pull request merged**
